Fix validation record
hiqdev/hipanel-module-dns pull request #1
Opened 2018-01-22 11:20 UTC by bladeroot

2018-01-23 08:51 UTC, SilverFire requested changes

2018-01-23 08:51 UTC, SilverFire commented on src/validators/MxValueValidator.php
> +        $model->$attribute = static::convertAsciiToIdn(strtolower($model->$attribute));
mb_strtolower

2018-03-23 08:15 UTC, SilverFire requested changes

2018-03-23 08:15 UTC, SilverFire commented on src/validators/FqdnValueValidator.php
> +        if (empty($result) && $this->trimTrailingDot) {
`parent::validateAttribute()` – void метод, `$result` всегда будет `null`

2018-05-09 08:09 UTC, hiqsol commented
Юра - доделывай!

2018-05-16 12:47 UTC, hiqsol approved these changes
вроде норм

2018-05-16 13:06 UTC, SilverFire approved these changes

2018-05-16 13:06 UTC, merged