show warning if domain has not any served nss
hiqdev/hipanel-module-dns pull request #20
Opened 2021-05-06 11:53 UTC by bladeroot

2021-05-06 14:38 UTC, hiqsol requested changes
так не пойдёт
дефолтные НСы это не глобальная настройка, а у каждого реселлера свои

2021-05-11 12:11 UTC, SilverFire commented on src/controllers/ZoneController.php
> +//            throw new NotFoundHttpException('DNS zone does not exist');
Почему решил перенести это на сторону View?

2021-05-11 12:11 UTC, SilverFire commented on config/params.php
> + * @copyright Copyright (c) 2015-2019, HiQDev (http://hiqdev.com/)
```suggestion
 * @copyright Copyright (c) 2015-2021, HiQDev (http://hiqdev.com/)
```

:)

2021-05-11 12:11 UTC, SilverFire commented on src/controllers/ZoneController.php
> +            'allModels' => $model === null ? null : $model->records,
Там же будет `foreach (null as ...` а это – Notice.
Нет?

2021-05-17 10:48 UTC, hiqsol commented on src/controllers/ZoneController.php
> +            'allModels' => $model === null ? null : $model->records,
```suggestion
            'allModels' => $model === null ? [] : $model->records,
```
так?

2021-05-18 15:07 UTC, SilverFire requested changes
Предлагаю из контроллера вызывать API:hdomainGetDefaultNSs, кешировать значение, передавать во вьюху. И тогда params можно выпилить

2021-06-11 08:06 UTC, hiqsol reviewed
не нравится но принимаю

2021-06-11 08:06 UTC, merged